//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int id { get; set; }
        public string masv { get; set; }
        public Nullable<int> tienganh { get; set; }
        public Nullable<int> tinhoc { get; set; }
        public Nullable<int> GDTC { get; set; }
    
        public virtual student student { get; set; }
    }
}
